---
- name: Ensure CentOS EPEL repos are available.
  include_role:
    name: geerlingguy.repo-epel

- name: Ensure IUS (Inline with Upstream Stable) is available.
  yum:
    name: https://centos7.iuscommunity.org/ius-release.rpm
    state: present

- name: Ensure pip is installed.
  include_role:
    name: geerlingguy.pip

- name: Ensure required packages are installed.
  when: ansible_distribution == 'CentOS'
  yum:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - coreutils
    - curl
    - git
    - make
    - ntp
    - openssh
    - sudo
    - vim
    - python-virtualenv
    - wget

- name: Install packages from pip.
  pip: "name={{ item }}"
  with_items:
    - awscli
    - boto
