---
alpine:
  # - aptitude
  - curl
  - shadow
  - git
  - openntpd
  - python2-dev # Required to install some pip packages.
  - runit
  # - ufw
  - py2-pip
  - virtualenv
  - vim
  - wget
  - openssh
    # - python-pip
    # - outils-sha256
    # - py2-pip
    # - py2-virtualenv

centos:
  # - aptitude
  - curl
  - shadow
  - git
  - openntpd
  - python2-dev # Required to install some pip packages.
  - runit
  # - ufw
  - py2-pip
  - vim
  - virtualenv
  - wget
  - openssh
