---
- name: Install yarn repo.
  become: yes
  shell: |
    yum-config-manager --add-repo=https://dl.yarnpkg.com/rpm/yarn.repo

- name: Install ripgrep repo.
  become: yes
  shell: |
    yum-config-manager --add-repo=https://copr.fedorainfracloud.org/coprs/carlwgeorge/ripgrep/repo/epel-7/carlwgeorge-ripgrep-epel-7.repo

- name: Install IUS (Inline with Upstream Stable).
  yum:
    name: https://centos7.iuscommunity.org/ius-release.rpm
    state: present

- name: Install python 3.
  yum:
    name: "{{ item }}"
  with_items:
    - python36u
    - python36u-pip

- name: Install the nice things.
  yum:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - mosh
    - neovim
    - nodejs
    - ripgrep
    - rsync
    - yarn

- name: Own `node_modules`
  become: yes
  shell: "chown -R {{ user }} /usr/lib/node_modules"

- name: Start docker daemon at boot.
  systemd:
    name: docker
    enabled: yes
  when: ansible_distribution == 'CentOS'

- name: Install RCM to manage dotfiles.
  become: yes
  include_role: name=rcm
  tags: rcm
  vars_files:
    - 'host_vars/main.yml'

- name: Install dotfiles.
  become: yes
  tags: dotfiles
  include_role: name=dotfiles
  vars_files:
    - 'host_vars/main.yml'

- name: Set up neovim.
  include_role: name=nvim