---
- name: Install the nice things.
  yum:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - go
    - mosh
    - neovim
    - nodejs
    - rsync

- name: Start docker daemon at boot.
  systemd:
    name: docker
    enabled: yes
  when: ansible_distribution == 'CentOS'
  # shell: rc-update add docker boot

- name: Update PATH.
  tags: rcm
  become: yes
  become_user: "{{ user }}"
  lineinfile:
    dest: /etc/environment
    state: present
    backrefs: yes
    regexp: PATH="$PATH:/usr/local/bin"
    line: PATH="$PATH:/usr/local/bin"

- name: Determine if RCM is installed.
  shell: if (hash lsrc &>/dev/null); then echo 1; else echo 0; fi
  register: rcm_installed
  ignore_errors: yes
  tags: rcm

- name: Install Thoughtbot's RCM to manage dotfiles.
  tags: rcm
  become: yes
  become_user: "{{ user }}"
  get_url:
    url: https://thoughtbot.github.io/rcm/dist/rcm-1.3.1.tar.gz
    dest: "$HOME"
  # when: not rcm_installed

- name: foo
  become: yes
  become_user: "{{ user }}"
  tags: rcm
  shell:
    tar -xvf "$HOME/rcm-1.3.1.tar.gz" && \
    cd rcm-1.3.1 && \
    ./configure && \
    make && \
    sudo make install
  # when: not rcm_installed

# - name: Determine if dotfiles directory exists.
#   become_user: "{{ user }}"
#   shell: ls "$HOME/dotfiles" &>/dev/null
#   register: dotfiles_cloned
#   ignore_errors: yes

- name: Pull dotfiles.
  become: yes
  become_user: "{{ user }}"
  tags: rcm
  git:
    repo: https://github.com/jessestuart/dotfiles
    dest: "$HOME/dotfiles"
  # when: not dotfiles_cloned

- name: Create vim plug directory.
  become: yes
  become_user: "{{ user }}"
  file:
    path: "$HOME/.local/share/nvim/site/autoload/plug.vim"
    state: directory
    owner: "{{ user }}"

- name: Install vim plug.
  become: yes
  become_user: "{{ user }}"
  tags:
    - deps
    - vim
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "$HOME/.local/share/nvim/site/autoload/plug.vim"
    owner: "{{ user }}"
    force: yes
