---
- name: Install OS-specific prequisites.
  include_tasks: "./os/{{ ansible_os_family }}.yml"

- name: Ensure cmake is present.
  become_user: root
  package: name=cmake state=present

- name: Install the nice things.
  become: yes
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    # - rust
    - mosh
    # - neovim
    - nodejs
    # - ripgrep
    # - yarn

- name: Own `node_modules`
  file:
    path: /usr/lib/node_modules
    state: directory
    owner: "{{ user }}"

- name: Install RCM to manage dotfiles.
  tags: rcm
  include_role: name=rcm

# - name: Set up neovim.
#   include_role: name=nvim

