---
- name: Install OS-specific prequisites.
  include_tasks: "./os/{{ ansible_os_family }}.yml"

- name: Ensure cmake is present.
  package: name=cmake state=present

- name: Install the nice things.
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - rust
    - mosh
    - neovim
    - nodejs
    - ripgrep
    - yarn

- name: Own `node_modules`
  become: yes
  file:
    path: /usr/lib/node_modules
    owner: "{{ user }}"

- name: Install RCM to manage dotfiles.
  become: yes
  tags: rcm
  include_role: name=rcm

- name: Set up neovim.
  include_role: name=nvim

