---
- name: Ensure yum-utils are installed.
  description: |
    This is required on some providers for the `yum-config-manager` command
    to be present.
  yum: name=yum-utils state=latest

- name: Ensure yarn repo is installed.
  become: yes
  shell: |
    yum-config-manager --add-repo=https://dl.yarnpkg.com/rpm/yarn.repo

- name: Ensure ripgrep repo is installed.
  become: yes
  shell: |
    # yamllint disable-line
    yum-config-manager --add-repo=https://copr.fedorainfracloud.org/coprs/carlwgeorge/ripgrep/repo/epel-7/carlwgeorge-ripgrep-epel-7.repo

- name: Install python 3.
  yum:
    name: "{{ item }}"
  with_items:
    - python36u
    - python36u-pip

- name: Install the nice things.
  yum:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - mosh
    - neovim
    - nodejs
    - ripgrep
    - rsync
    - yarn

- name: Own `node_modules`
  become: yes
  shell: "chown -R {{ user }} /usr/lib/node_modules"

# - name: Start docker daemon at boot.
#   systemd:
#     name: docker
#     enabled: yes
#   when: ansible_distribution == 'CentOS'

- name: Install RCM to manage dotfiles.
  become: yes
  tags: rcm
  vars_files: 'host_vars/main.yml'
  include_role: name=rcm

- name: Set up neovim.
  include_role: name=nvim
