---
- name: Install zsh.
  package: name=zsh

- name: Install Prezto.
  git:
    repo: https://github.com/sorin-ionescu/prezto
    dest: "/home/{{ user }}/.zprezto"
    recursive: yes
    force: yes

- name: Own Prezto directory for user.
  file:
    path: "/home/{{ user }}/.zprezto"
    owner: "{{ user }}"
    state: directory
    mode: "u+rw"

- name: Set default shell for user.
  become: yes
  user:
    name: "{{ user }}"
    shell: /bin/zsh
