---
- name: Update PATH to include `/usr/local/bin`.
  become: yes
  become_user: "{{ user }}"
  lineinfile:
    dest: /etc/environment
    state: present
    backrefs: yes
    regexp: PATH="$PATH:/usr/local/bin"
    line: PATH="$PATH:/usr/local/bin"

- name: Determine if RCM is installed.
  become: yes
  become_user: "{{ user }}"
  shell: lsrc &>/dev/null
  register: rcm_installed
  ignore_errors: yes
  changed_when: no

- name: Pull down RCM tarball.
  become: yes
  when: rcm_installed|failed
  get_url:
    url: https://thoughtbot.github.io/rcm/dist/rcm-1.3.1.tar.gz
    dest: /tmp

- name: Unarchive RCM tarball.
  when: rcm_installed|failed
  unarchive:
    src: /tmp/rcm-1.3.1.tar.gz
    dest: /tmp
    remote_src: yes

- name: Build and install the RCM binaries.
  when: rcm_installed|failed
  become: yes
  shell: |
    cd /tmp/rcm-1.3.1 && \
    ./configure && \
    make && \
    make install
