---
hostname: homemaker
user: jesse

nginx_server_name: 192.168.0.104
# Internal drone ui http url used by nginx to proxy traffic.
# For example: http://localhost:8000
nginx_internal_host: http://localhost:8000
