---
version: 2
jobs:
  build:
    working_directory: ~/homemaker
    machine: true

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Vagrantfile" }}
            - v1-dependencies-

      - run:
          command: chmod +x ./provision.sh && sudo ./provision.sh

      - run:
          command: ansible-galaxy install -r ansible/requirements.yml

      # The 'test' here is that Vagrant can build the box. We should add more
      # steps after this to ensure the software we installed is in working
      # order.
      - run:
          command: vagrant up default --provision

      ---
version: 2

jobs:
  build:
    working_directory: /home/vagrant
    docker:
      - image: jessestuart/vagrant-build-base:latest
        user: root

    steps:
      - checkout

      - run:
          name: Validate Vagrantfile
          command: |
            vagrant validate

      - setup_remote_docker

      - run:
          name: Link cache.
          command: |
            set -x
            if [ -z "$CIRCLE_BUILD_NUM" ]; then
              mkdir -p /home/vagrant/cache/vagrant
              ln -sf  /home/vagrant/cache/vagrant \
                /home/vagrant/.vagrant/machines/default/cache
            fi

      # This cache is produced by the vagrant-cachier plugin. It created a
      # synced folder named /tmp/vagrant-cache that primarily holds OS
      # packages, but this project also keeps other large downloads there. The
      # cache key includes the revision because any of the Vagrantfile or
      # Ansible files can influence the cache.  The second key will reuse the
      # cache from a previous build.
      - restore_cache:
          keys:
            - v1-vagrant-{{ .Branch }}-{{ .Revision }}
            - v1-vagrant-{{ .Branch }}-
            - v1-vagrant-

      - run:
          command: |
            vagrant up docker

      - save_cache:
          keys:
            - v1-vagrant-{{ .Branch }}-{{ .Revision }}
            - v1-vagrant-{{ .Branch }}-
            - v1-vagrant-
          paths:
            - /home/vagrant/.vagrant/machines/default/cache
