version: 2
jobs:
  build:
    working_directory: /home/linux-dev-workstation
    docker:
      - image: jessestuart/vagrant-build-base:latest
        user: root

    steps:
      - checkout

      - run:
          name: Validate Vagrantfile
          command: |
            vagrant validate

      - setup_remote_docker

      - run:
          name: Link Developer Workstation Cache
          command: |
            set -x
            if [ -z "$CIRCLE_BUILD_NUM" ]; then
              mkdir -p /home/linux-dev-workstation/cache/vagrant
              ln -sf  /home/linux-dev-workstation/cache/vagrant /home/linux-dev-workstation/.vagrant/machines/default/cache
            fi

      # This cache is for the docker images. Layer caching is early, we use a
      # tarball created by `docker save` to cache our images.
      - restore_cache:
          keys:
            - v4-dockerimage-{{ .Branch }}-{{ checksum "Vagrantfile" }}}
            - v4-dockerimage-{{ .Branch }}-
            - v4-dockerimage-

      # This cache is produced by the vagrant-cachier plugin. It created a
      # synced folder named /tmp/vagrant-cache that primarily holds OS
      # packages, but this project also keeps other large downloads there.  The
      # cache key includes the revision because any of the Vagrantfile or
      # Puppet files can influence the cache.  The second key will reuse the
      # cache from a previous build.
      - restore_cache:
          keys:
            - v4-vagrant-{{ .Branch }}-{{ .Revision }}
            - v4-vagrant-{{ .Branch }}-
            - v4-vagrant-

      - run:
          name: Restore Docker Public Image Cache
          command: |
            set -x
            if [[ -e /home/linux-dev-workstation/cache/docker/image.tar ]]; then
              docker load -i /home/linux-dev-workstation/cache/docker/image.tar
            fi

      # The 'test' here is that Vagrant can build the box. We should add more
      # steps after this to ensure the software we installed is in working
      # order.
      # We are adding '--provision' for testing locally and iterating.
      - run:
          name: Test Vagrant Up
          command: |
            vagrant up --provider docker --provision

      - run:
          name: Build Docker Public Image Cache
          command: |
            set -x
            mkdir -p /home/linux-dev-workstation/cache/docker
            docker save \
              $(docker images | grep -v 'REPOSITORY\|none' | cut -d ' ' -f 1) \
              > /home/linux-dev-workstation/cache/docker/image.tar

      - save_cache:
          key: v4-dockerimage-{{ .Branch }}-{{ checksum "Vagrantfile" }}
          paths:
            - /home/linux-dev-workstation/cache/docker

      # We must use rsync for synced folder because circleci remote docker
      # cannot do volume mapping. We need to copy the cached files back into
      # this container for storing in the cache.
      - run:
          name: Copy Vagrant Cache
          command: |
            set -x
            rm -rf /home/linux-dev-workstation/.vagrant/machines/default/cache
            # yamllint ignore-line
            docker cp linux-dev-workstation:/tmp/vagrant-cache /home/linux-dev-workstation/.vagrant/machines/default/cache

      - save_cache:
          key: v4-vagrant-{{ .Branch }}-{{ .Revision }}
          paths:
            - /home/linux-dev-workstation/.vagrant/machines/default/cache
