---
version: 2
jobs:
  build:
    working_directory: /home/linux-dev-workstation
    docker:
      - image: jessestuart/vagrant-build-base:latest
        user: root

    steps:
      - checkout
      - setup_remote_docker

      - run:
          command: |
            yum install -y ansible

      - run:
          command: |
            ansible-galaxy install -r ansible/requirements.yml

      # The 'test' here is that Vagrant can build the box. We should add more
      # steps after this to ensure the software we installed is in working
      # order.
      - run:
          name: Test Vagrant Up
          command: |
            vagrant up docker --provider docker --provision
