---
version: 2
jobs:
  build:
    working_directory: ~/homemaker
    docker:
      - image: jessestuart/vagrant-build-base
        user: root
    environment:
      - PACKAGES: "ansible build-essential curl dkms python sudo wget"
    steps:
      - checkout

      - setup_remote_docker

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Vagrantfile" }}
      - run:
          command: |
            vagrant validate

      - run:
          command: |
            apt-get update -y
            apt-get install -y $PACKAGES linux-headers-$(uname -r)


      # The 'test' here is that Vagrant can build the box. We should add more
      # steps after this to ensure the software we installed is in working
      # order.
      - run:
          name: Test Vagrant Up
          command: |
            vagrant up default --provision
