---
version: 2
jobs:
  build:
    working_directory: /home/linux-dev-workstation
    docker:
      - image: ubuntu:xenial
        user: root

    steps:
      - checkout
      - setup_remote_docker

      - run:
          command: |
            wget -q -O - http://download.virtualbox.org/virtualbox/debian/oracle_vbox.asc | sudo apt-key add -
            sudo sh -c 'echo "deb http://download.virtualbox.org/virtualbox/debian precise non-free contrib" >> /etc/apt/sources.list.d/virtualbox.org.list'
            sudo apt-get update -y
            sudo apt-get install -y linux-headers-$(uname -r) build-essential virtualbox dkms python ansible
            pushd /tmp
            wget http://download.virtualbox.org/virtualbox/4.3.36/Oracle_VM_VirtualBox_Extension_Pack-4.3.36.vbox-extpack
            sudo VBoxManage extpack install Oracle_VM_VirtualBox_Extension_Pack-4.3.36.vbox-extpack
            wget https://releases.hashicorp.com/vagrant/2.0.1/vagrant_2.0.1_x86_64.deb
            sudo dpkg -i vagrant_2.0.1_x86_64.deb
            popd

      - run:
          command: |
            ansible-galaxy install -r ansible/requirements.yml

      # The 'test' here is that Vagrant can build the box. We should add more
      # steps after this to ensure the software we installed is in working
      # order.
      - run:
          name: Test Vagrant Up
          command: |
            vagrant up docker --provision
