# ========================================================================
# `ansible` role contains prequisite dependencies needed to provision via
# Ansible over SSH.
# ========================================================================
---
- name: Check OS.
  raw: test -e /etc/debian_version
  register: is_debian_based

- name: End play if OS is not Debian-based.
  meta: end_play
  when: is_debian_based.rc != 0

# Reference: http://xnoder.github.io/ansible-xenial/
- name: Check if Python is installed.
  raw: python --version
  ignore_errors: yes
  changed_when: false
  register: has_python

- name: End play if python is already installed.
  meta: end_play
  when: has_python is succeeded

- name: Ensure that python2.7 is installed.
  raw: sudo apt-get install -yq python2.7
  when: apt_result is failed

- name: Create softlink for python 2.7.
  raw: ln -s /usr/bin/python2.7 /usr/bin/python

- name: Verify that python installation was successful.
  raw: python --version
  changed_when: false
