---
- name: Determine if dotfiles directory exists.
  become: yes
  become_user: "{{ user }}"
  stat:
    path: "$HOME/dotfiles"
  register: dotfiles_dir

- name: Create dotfiles directory.
  become: yes
  become_user: "{{ user }}"
  when: not dotfiles_dir.stat.exists
  file:
    path: "$HOME/dotfiles"
    state: directory

- name: Pull dotfiles.
  become: yes
  become_user: "{{ user }}"
  tags: rcm
  when: not dotfiles_dir.stat.exists
  git:
    repo: https://github.com/jessestuart/dotfiles
    dest: "$HOME/dotfiles"
    force: yes

- name: UNLEASH THE DOTFILES!
  become: yes
  become_user: "{{ user }}"
  shell: rcup -d "$HOME/dotfiles"
  ignore_errors: yes
