---
- name: Determine if dotfiles directory exists.
  become: yes
  become_user: "{{ user }}"
  stat: path="$HOME/dotfiles"
  register: dotfiles_dir

- name: Create dotfiles directory.
  become: yes
  become_user: "{{ user }}"
  when: not dotfiles_dir.stat.exists
  file:
    path: "$HOME/dotfiles"
    state: directory

# TODO(20180107) Abstract this out into a variable.
- name: Pull dotfiles.
  become: yes
  become_user: "{{ user }}"
  git:
    repo: https://github.com/jessestuart/dotfiles
    dest: "$HOME/dotfiles"
    force: yes

- name: UNLEASH THE DOTFILES!
  become: yes
  become_user: "{{ user }}"
  shell: /usr/local/bin/rcup -d "$HOME/dotfiles"
  ignore_errors: yes
