---
- name: Determine tmux version, if installed.
  shell: tmux -V | sed 's/tmux //' || false
  ignore_errors: true
  register: tmux_version
  changed_when: no

- name: End play if tmux is already up-to-date.
  meta: end_play
  when: tmux_version is defined and tmux_version == '2.6'

- name: Ensure tmux dependencies are installed.
  become: yes
  package:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - gcc
    - libevent
    - ncurses

- name: Ensure CentOS-specific tmux dependencies are installed.
  become: yes
  package:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - libevent-devel
    - ncurses-devel
  when: ansible_distribution == 'CentOS'

- name: Pull down tmux 2.6 release.
  become: yes
  get_url:
    url: https://github.com/tmux/tmux/releases/download/2.6/tmux-2.6.tar.gz
    dest: /tmp/tmux-2.6.tar.gz

- name: Create temp installation directory.
  file:
    name: /tmp/tmux-2.6
    state: directory

- name: Unarchive tmux tarball.
  become: yes
  unarchive:
    src: /tmp/tmux-2.6.tar.gz
    dest: /tmp
    remote_src: yes

- name: Install tmux.
  become: yes
  shell: |
    cd /tmp/tmux-2.6 && \
    LDFLAGS="-L/usr/local/lib -Wl,-rpath=/usr/local/lib" \
    ./configure --prefix=/usr/local && \
    make && \
    make install

- name: Remove temp installation directory.
  file:
    name: /tmp/tmux-2.6
    state: absent

- name: Remove tmux tarball.
  file:
    name: /tmp/tmux-2.6.tar.gz
    state: absent
