---
# ====================================================================
# To protect against man-in-the-middle attacks, at least use the local
# (control) machine to find the right github RSA public key.
# ====================================================================
- name: Ensure GitHub is a known host
  lineinfile:
    dest: /etc/ssh/ssh_known_hosts
    create: yes
    state: present
    line: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
    regexp: "^github\\.com"

# =====================================
# Accept SSH env variables for AWS CLI.
# =====================================
- name: Add AcceptEnv to /etc/ssh/sshd_config
  lineinfile:
    dest: /etc/ssh/sshd_config
    create: yes
    state: present
    line: 'AcceptEnv AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_DEFAULT_REGION #AWS Creds'
    regexp: '#AWS Creds'
  when: ansible_virtualization_type != 'docker'
  notify:
    - Restart ssh service

- name: Install docker-py.
  become: yes
  pip: name=docker-py state=latest
  tags: hostname

# Set the hostname as specified in the inventory.
- name: Set /etc/hostname
  gather_facts: yes
  become: yes
  tags: hostname
  hostname: name="{{ hostname }}"
  when: ansible_virtualization_type != 'docker'

# This is required to be in sync because many commands, such as sudo,
# may fail otherwise.
- name: Register hostname in /etc/hosts
  tags: hostname
  when: ansible_virtualization_type != 'docker'
  lineinfile:
    state: present
    dest: /etc/hosts
    regexp: '127.0.0.1'
    line: "127.0.0.1 localhost {{ hostname }}"

# - name: Remove root public keys
#   file:
#     state: absent
#     path: /root/.ssh/authorized_keys

# - name: Deny root login
#   lineinfile:
#     state: present
#     dest: /etc/ssh/sshd_config
#     regexp: PermitRootLogin
#     line: 'PermitRootLogin no'
#   notify:
#     - Restart ssh service
