---
- name: Ensure tmux dependencies are installed.
  become: yes
  yum:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - libevent
    - libevent-devel
    - ncurses
    - ncurses-devel

- name: Pull down tmux 2.6 release.
  become: yes
  get_url:
    url: https://github.com/tmux/tmux/releases/download/2.6/tmux-2.6.tar.gz
    dest: "/tmp/tmux-2.6.tar.gz"

- name: Create temp installation directory.
  file:
    name: /tmp/tmux-2.6
    state: directory

- name: Unarchive tmux tarball.
  become: yes
  unarchive:
    src: /tmp/tmux-2.6.tar.gz
    dest: /tmp/tmux-2.6
    creates: "$HOME/tmux-2.6"
    remote_src: yes

- name: Install tmux.
  become: yes
  shell: |
    cd /tmp/tmux-2.6 && \
    LDFLAGS="-L/usr/local/lib -Wl,-rpath=/usr/local/lib" ./configure --prefix=/usr/local && \
    make && \
    sudo make install

- name: Remove temp installation directory.
  file:
    name: /tmp/tmux-2.6
    state: absent