---
- name: Determine tmux version, if installed.
  shell: (hash tmux&>/dev/null) && tmux -V | sed 's/tmux //' || false
  ignore_errors: true
  register: tmux_version

- name: Ensure tmux dependencies are installed.
  when: tmux_version != '2.6'
  become: yes
  yum:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - gcc
    - libevent
    - libevent-devel
    - ncurses
    - ncurses-devel

- name: Pull down tmux 2.6 release.
  when: tmux_version != '2.6'
  become: yes
  get_url:
    url: https://github.com/tmux/tmux/releases/download/2.6/tmux-2.6.tar.gz
    dest: /tmp/tmux-2.6.tar.gz

- name: Create temp installation directory.
  when: tmux_version != '2.6'
  file:
    name: /tmp/tmux-2.6
    state: directory

- name: Unarchive tmux tarball.
  when: tmux_version != '2.6'
  become: yes
  unarchive:
    src: /tmp/tmux-2.6.tar.gz
    dest: /tmp
    remote_src: yes

- name: Install tmux.
  when: tmux_version != '2.6'
  become: yes
  shell: |
    cd /tmp/tmux-2.6 && \
    LDFLAGS="-L/usr/local/lib -Wl,-rpath=/usr/local/lib" \
    ./configure --prefix=/usr/local && \
    make && \
    make install

- name: Remove temp installation directory.
  when: tmux_version != '2.6'
  file:
    name: /tmp/tmux-2.6
    state: absent

- name: Remove tmux tarball.
  when: tmux_version != '2.6'
  file:
    name: /tmp/tmux-2.6.tar.gz
    state: absent