---
- name: Ensure tmux dependencies are installed.
  become: yes
  yum:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - libevent
    - libevent-devel
    - ncurses
    - ncurses-devel

- name: Pull down tmux 2.6 release.
  become: yes
  become_user: "{{ user }}"
  get_url:
    url: https://github.com/tmux/tmux/releases/download/2.6/tmux-2.6.tar.gz
    dest: "$HOME/tmux-2.6.tar.gz"

- name: Unarchive tmux tarball.
  become: yes
  become_user: "{{ user }}"
  unarchive:
    src: "$HOME/tmux-2.6.tar.gz"
    dest: "$HOME/tmux-2.6"
    creates: "$HOME/tmux-2.6"
    remote_src: yes

- name: Install tmux.
  become: yes
  shell: |
    cd tmux-2.6 && \
    LDFLAGS="-L/usr/local/lib -Wl,-rpath=/usr/local/lib" ./configure --prefix=/usr/local && \
    make && \
    sudo make install
