hostname: homemaker
user: jesse

# server_setup_ssl: false
# server_ssl_key_path: "/etc/nginx/ssl/drone-ci.key"
# server_ssl_cert_path: "/etc/nginx/ssl/drone-ci.crt"

nginx_server_name: 192.168.0.104
# Internal drone ui http url used by nginx to proxy traffic.
# For example: http://localhost:8000
nginx_internal_host: http://localhost:8000

# List of users with admin access to the drone.
# @see http://docs.drone.io/user-management/
# drone_admins: "jessestuart"
