---
- name: Ensure python 2.7 is installed.
  raw: test -e /usr/bin/python || (yum -y update; yum -y install python)

- name: Ensure pip prerequisites are installed.
  include_role:
    name: geerlingguy.repo-epel

- name: Ensure pip is installed.
  include_role:
    name: geerlingguy.pip

- name: Ensure required packages are installed.
  when: ansible_distribution == 'CentOS'
  yum:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - coreutils
    - curl
    - git
    - make
    - ntp
    - openssh
    - sudo
    - vim
    - python-virtualenv
    - wget

- name: Install packages from pip.
  pip: "name={{ item }}"
  with_items:
    # For interacting with AWS.
    - awscli
    # Boto is needed to perform some AWS tasks, like pulling from S3.
    - boto

# Set the hostname as specified in the inventory.
- name: Set /etc/hostname
  tags: hostname
  hostname:
    name: "{{ hostname }}"

# This is required to be in sync because many commands, such as sudo,
# may fail otherwise.
- name: Register hostname in /etc/hosts
  lineinfile:
    state: present
    dest: /etc/hosts
    regexp: '127.0.0.1'
    line: "127.0.0.1 localhost {{ hostname }}"
