- name: Ensure required packages are installed.
  apk:
    pkg: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    # - aptitude
    - curl
    - shadow
    - git
    - openntpd
    - python2-dev # Required to install some pip packages.
    - runit
    # - ufw
    - py2-pip
    - vim
    - wget
    - openssh

- name: Install AWS-related packages from pip.
  pip: name={{ item }}
  with_items:
    # For interacting with AWS.
    - awscli
    # Boto is needed to perform some AWS tasks, like pulling from S3.
    - boto
